apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kolkhis-backend
  namespace: kolkhis
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - api.euxine.eu
      secretName: kolkhis-backend-tls
  rules:
    - host: api.euxine.eu
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kolkhis-backend
                port:
                  number: 80
