apiVersion: apps/v1
kind: Deployment
metadata:
  name: kolkhis-backend
  namespace: kolkhis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kolkhis-backend
  template:
    metadata:
      labels:
        app: kolkhis-backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/euxinedata/kolkhis-backend:90e9995
          env:
            - name: DATABASE_URL
              value: postgresql+asyncpg://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/$(POSTGRES_DB)
          envFrom:
            - secretRef:
                name: postgres-credentials
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
