apiVersion: apps/v1
kind: Deployment
metadata:
  name: kolkhis
  namespace: kolkhis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kolkhis
  template:
    metadata:
      labels:
        app: kolkhis
    spec:
      containers:
        - name: kolkhis
          image: ghcr.io/euxinedata/kolkhis:e702981
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
